version: '3.8'

services:
  facade-service:
    build: ./facade-service
    ports:
      - "8080:8000"
    depends_on:
      - logging-service
      - counter-service

  logging-service:
    build: ./logging-service
    ports:
      - "8081:8000"

  counter-service:
    build: ./counter-service
    ports:
      - "8082:8000"